Refactored BGT60 Lib & Basic DAQ Functionality
HCL-Hbot/mmWave_bgt60lrxx pull request #1
Opened 2024-04-04 17:18 UTC by RichardKroesen

### Brief
First of all, keep in mind that I'm developing with rapid prototyping mindset, altough I started the BGT60 library from scratch. So yeah, here and there could be some ugly implementation and/or commented sections. 

### Functionality
After banging my head for over a month already and confusion about how Infineon initliazes the radar thing. I figured out that the SPI mode is meant for configuration only, and not a state from which you can operate. 

So in short this is what this program does:
1. Reset the BGT60. 
2. Configure default values and desired values in the registers, and put it in Continuous Wave autonomous mode (CW). 
3. In the super loop the I and Q components are read, I check if they are not zero, which is a ugly way for now to filter out invalid frames.
4. The streamer sends the read values in csv format over uart. So that I can start native Python dev yey, where I can do my dataprocessing and feature extraction.

### Next Steps
Here is an overview of my next intentions after this PR in the context of the Radar dev: 
- Start dev for native samples log/acquisition so that feature extraction math models could be tested. 
- Start with a cyberphysical low-frequency displacement setup with a speaker or electrodynamic shaker for stimulate respiratory movement. 
- Integrate the native daq and the vital signs model into one application. 
- Add functionality for just human prescence detection, so expanding the Radar functionality. 

### Final Notice
I'm going to try to create a POC setup for the Sprint 2 deadline, so that we can demonstrate the the vital signs recognition. And hopefully in sprint 3 we can integrate it into the robot, and fine-tune the issues.

2024-04-08 09:41 UTC, Hoog-V requested changes
Wow! You put a lot of effort in to this. I saw too many things that I would generally not do, I am really way too conservative for this (gimme C instead)  :) Please do something about those variadic functions, the huge terrible struct, some function/naming things, documentation of function usage, macro's that cannot be overridden and next time it is more useful if you made the PR smaller. Now I skipped really fast over your code so I had not really had the time to look at the details!

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/include/bgt60ltr11XXX_regs.hpp
> +};
These should be separate enums instead! This is ambiguous

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/include/bgt60ltr11XXX_regs.hpp
> +};
Here you did it right :) haha

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/include/bgt60ltr11XXX_typedef.hpp
> +} S2GO_RADAR_BGT60LTR11_Config_t;
What is this name haha

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        for (uint16_t i = 0; i < 2048; i++) {
Why 2048? This is a huge number haha

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +            sleep_ms(1);
I hate sleeps in library's. Why? When using a rtos for example sleep_ms() will not sleep the task!
It will block the task and mess with the timing of the other tasks in the system. And the user of the library might not know until he notices his timing is off.

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +    }
Cool! For the untrained eye this is some black c++ metaprogramming magic

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        for (const auto& fv : fieldsValues) {
Perks of using variadic functions!

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        return getField(regValue, field);
don't put this in a return statement! Make a separate variable please and return the variable. As this is a hell to debug

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        return getField(regValue, field);
Besides this you can make this a macro and call it bitfield_is_set() or such.. getField was kinda unclear at first glance

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        return 0;
don't know the specifics, but you can make STATUS_GSR_REG a ternary and do the return of channel_result. As this value will probably always yield 0 if unsuccessful. Right?

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +    const uint16_t BGT60_DRIVER::getRegisterField(uint8_t registerAddress, const RegisterField& field) {
I would have given this function another name:
read_register() or such. As getRegisterField did not seem clear to me at first glance

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        }
If measurements are not valid! Why process further... Just return as it saves some precious cpu cycles

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        sleep_ms(50);
No not more sleeps

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        sleep_ms(50);
Use platform macro's (maybe using buildsystem) or don't use them at all

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        data_to_send[0] = ((reg & 0x7F) << BIT_ONE) | SPI_READ_BIT;
You really don't need to define a macro called BIT_ONE, maybe make this a macro if you don't trust it:

```c
#define SET_SPI_ADDR(addr, read_wr_bit) (((reg & 0x7F) << 1) | SPI_READ_BIT)

...

data_to_send[0] = SET_SPI_ADDR(reg, SPI_READ_BIT);
```

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        data_to_send[1] = (value >> BYTE) & BYTE_MASK; // MSB of the value to write
Same for this! Make a macro called:

GET_LOWER_BITS_OF_SHORT(x)

and 

GET_UPPER_BITS_OF_SHORT(x)

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        const uint8_t spiAddr = ((reg & 0x7F) << BIT_ONE) & ~(SPI_READ_BIT);
Why do the ~(SPI_READ_BIT) at the first place! You can leave this out.. The rest of the bits will be set to zero regardless

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        return (static_cast<uint16_t>((received_data[1]) << BYTE) | static_cast<uint16_t>(received_data[2]));
Make this a separate const variable, please...

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +        if (STATUS_GSR0_REG == 4) {
Again a ternary would be a better bet

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +            return BIT_ONE;
haha return BIT_ONE;
:p

2024-04-08 09:41 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +    const inline constexpr uint16_t BGT60_DRIVER::getField(const uint16_t reg, const RegisterField field) {
Rename this function

2024-04-08 09:41 UTC, Hoog-V commented on streamer/include/UART_streamer.hpp
> +    }
I am gonna call you the variadic man! Seriously used it once, now it is everywhere.  **I need more coffee**

2024-04-08 09:41 UTC, Hoog-V commented on streamer/include/UART_streamer.hpp
> +        ss << value;
Wtf, you did not even make it inline.

2024-04-08 09:41 UTC, Hoog-V commented on streamer/include/UART_streamer.hpp
> +    }
Did I tell you already that I don't like C++ streams. Why? They sometimes use the heap and they are slow as molasses on some platforms. Because the implementation of these functions differ between platforms and stdlib implementations

2024-04-08 09:45 UTC, Hoog-V commented on streamer/include/UART_streamer.hpp
> +        ss << value;
Why did you even make this a separate function in the first place?

2024-04-12 09:01 UTC, RichardKroesen commented on CMakelists.txt
> +cmake_minimum_required(VERSION 3.11)
Thanks for the tip :)

2024-04-12 09:04 UTC, RichardKroesen commented on bgt60/include/bgt60ltr11XXX_driver.hpp
> +#define SPI_RS      0  // Reset Line
Well, yea yea. I mentioned I'm rapid prototyping, but I understand your point.

I will change it so that it can be a constructor parameter.

2024-04-12 09:31 UTC, RichardKroesen commented on bgt60/include/bgt60ltr11XXX_driver.hpp
> +    const static uint16_t ReadAD_SingleChannelResult(const ADC_REG_CHANNELS channel);
Fair point.

2024-04-12 09:33 UTC, RichardKroesen commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +            return BIT_ONE;
? It is intentional, maybe it is strange for you. But I always use uint8_t for booleans, because they are a byte long at minimum.

2024-04-12 09:34 UTC, RichardKroesen commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +            return BIT_ONE;
Otherwhise I can start with typedef hell, and create a TRUE var... But I assume that it is intuitive for a eser to know what bit_one means in this context.

2024-04-12 09:36 UTC, RichardKroesen commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +    const inline constexpr uint16_t BGT60_DRIVER::getField(const uint16_t reg, const RegisterField field) {
Haha, I'm not a creative writer. So I will try something else

2024-04-12 09:39 UTC, RichardKroesen commented on streamer/include/UART_streamer.hpp
> +    }
I also need more coffee ;D 

💙 Modern C++

2024-04-12 09:47 UTC, RichardKroesen commented on streamer/include/UART_streamer.hpp
> +    }
Okey, I get it. 

Yeah, it a quick and not very stable implementation. I'm following our intentions of working on the technical level of 3. 

It is for sure not near a production ready code. I'm trying to put only 3x9 and here and maybe couple of evenings. So I'm trying to make it functional and globally well structured but not well optimized on every line. 

Anyhow thanks for the tip about streams ;)

2024-04-12 10:39 UTC, Hoog-V commented on bgt60/src/bgt60ltr11XXX_driver.cpp
> +            return BIT_ONE;
No just do this:

```c
return 1;  /* Fault/Ok state */
```

You don't need to hide 1 in to a macro :p that was what I meant hihi.

I use uint8_t for booleans too as they differ for each architecture (some platforms use uint32_t for bools)

Please for god sake don't make it a typedef, you are not like EWOUT! *Well I hope!

2024-04-12 10:41 UTC, Hoog-V approved these changes
Well, I went a bit above and beyond in my previous review as most points mentioned were release/non-prototype/best-practices related advice. But please do document those variadic functions well. That is my only advice. And not for this but for future check with Godbolt what the compiler takes out of your variadic stuff. I am really curious.

2024-04-12 11:20 UTC, RichardKroesen commented
> Well, I went a bit above and beyond in my previous review as most points mentioned were release/non-prototype/best-practices related advice. But please do document those variadic functions well. That is my only advice. And not for this but for future check with Godbolt what the compiler takes out of your variadic stuff. I am really curious.

I get it and I'm thankful for the honest review! 

Ofcourse you understand that I need to play along and also defend my decisions here XD. However, please let's keep in mind that we are working on a prototype on the **`Technical Level 3`**, as we debated about the difference many times already in the upcoming PRs.

Sure, we can start with production ready code. But then I would really use that many sdk's, besides I don't see any performance issues at this moment so why bother about every single performance optimalization.

For you maybe interesting to know my philoshop: I think it you should not bother about optimalization that much, especially not in the beginning. Why, well several reasons:

1. Why optimize before this is necessary? I mean refactoring and rearranging will definitely happen sometime in the future. Sure if you use intuitive best-practises and are aware of your implementation consequences (which I'm, and tbh most of the times I'm lazy haha).
2. Efficient code can become even more complex, and for sure more challenging. 
4. MCU become more powerful, for the same price. In the time you are optimizating your system, you could have spend a bit more for the hardware and got a more well useable application for scaleability (at the bottom line, you have less dev overhead but more production cost, yeah depends on project financing if it is worth it etc..). In other words: why constrain yourself, if at the end it does not matter. (Why I'm not a huge fan of LoRa oof). 

Anyhow thanks for the tip of being more careful with the variadic functions. I think this could be indeed interesting to dive into what the compiler does with it indeed.

2024-04-14 11:17 UTC, Hoog-V commented
You have some great points in your philosophy, but still I strongly disagree with some points:

Haha gonna be brutally honest here..

Point 1: Why optimize before this is necessary?
This is not optimization, these are some best-practices advice, adhering to compatibility helps later adaptation and portability of the library your writing! This becomes more like a personal taste thing then an optimization thing.
Besides this the code practices you used where also optimizations, not for speed but for your own code-ability (haha not for others though, ask someone else in our classroom to add functionality to your code).

Using non-standard Variadic function stuff is a waste of time imo (when talking about optimization). You already had to define all kinds of const and statics to even use these functions. Then you had to do some black magic c++ (that not even each mcu architecture/vendor supports well), to just be able to yank each register by label in to function and end up with the same repetitive shit you would have had regardless. So what's the point of doing this! 

Point 2: Efficient code can become even more complex, and for sure more challenging.
This is a point I strongly disagree on. Like come on!  Look at your own code and compare it to the original library of infineon. Is it really that more readable to the average programmer? No! Is infineons library more efficient? Yes! 

Point 3: MCU become more powerful, for the same price. In the time you are optimizing your system, you could have spend a bit more for the hardware and got a more well use-able application for scalability.

Yes, MCU's are getting cheaper and more powerful. Yes not going mayhem with optimizations helps scalability. But writing your code in a way that it can be optimized helps a lot. And this code needs a complete rewrite if I want to optimize things, so NO! It is not scalable in that sense (I would even dare to say, that even Ewout's code is more optimizable (but his toolchain is shit)). So no this is not saving your company costs in the future, as having knowledge of the concepts you used in your programming are not used a lot in embedded programming (among embedded and electrical engineers) and can not be easily optimised in the future. Thus will result in a complete or partial rewrite if someone wants to add features or optimize the library. Adding serious tech debt.

The middle ground I believe is just using C++ with basic template's or classes w. inheritance and defines. This approach makes sure it can be easily optimized. Besides this adds more then enough room for easy scaling, and well use-able applications.  Writing this should not take more or less time than your application, it is just a mindset! Not an optimization.

2024-04-14 20:41 UTC, RichardKroesen commented
> You have some great points in your philosophy, but still I strongly disagree with some points:
> 
> Haha gonna be brutally honest here..
> 
> Point 1: Why optimize before this is necessary? This is not optimization, these are some best-practices advice, adhering to compatibility helps later adaptation and portability of the library your writing! This becomes more like a personal taste thing then an optimization thing. Besides this the code practices you used where also optimizations, not for speed but for your own code-ability (haha not for others though, ask someone else in our classroom to add functionality to your code).
> 
> Using non-standard Variadic function stuff is a waste of time imo (when talking about optimization). You already had to define all kinds of const and statics to even use these functions. Then you had to do some black magic c++ (that not even each mcu architecture/vendor supports well), to just be able to yank each register by label in to function and end up with the same repetitive shit you would have had regardless. So what's the point of doing this!
> 
> Point 2: Efficient code can become even more complex, and for sure more challenging. This is a point I strongly disagree on. Like come on! Look at your own code and compare it to the original library of infineon. Is it really that more readable to the average programmer? No! Is infineons library more efficient? Yes!
> 
> Point 3: MCU become more powerful, for the same price. In the time you are optimizing your system, you could have spend a bit more for the hardware and got a more well use-able application for scalability.
> 
> Yes, MCU's are getting cheaper and more powerful. Yes not going mayhem with optimizations helps scalability. But writing your code in a way that it can be optimized helps a lot. And this code needs a complete rewrite if I want to optimize things, so NO! It is not scalable in that sense (I would even dare to say, that even Ewout's code is more optimizable (but his toolchain is shit)). So no this is not saving your company costs in the future, as having knowledge of the concepts you used in your programming are not used a lot in embedded programming (among embedded and electrical engineers) and can not be easily optimised in the future. Thus will result in a complete or partial rewrite if someone wants to add features or optimize the library. Adding serious tech debt.
> 
> The middle ground I believe is just using C++ with basic template's or classes w. inheritance and defines. This approach makes sure it can be easily optimized. Besides this adds more then enough room for easy scaling, and well use-able applications. Writing this should not take more or less time than your application, it is just a mindset! Not an optimization.

Oof, I will add my final notes and quickly shut this PR off because it was at the start escalated lol XD. 

1) jeje, savy. But then you get boring code, and then I would need to program with coffee and be in an office envionment. And not in a chaotic mess at HCL. Or I couldn't contribute in late hours (halve a sleep haha). 

Tbh I never use this structure, I'm just playing around hihi. I will never reach the point of complete functionality, which I was aware off at the start so don't carefully architecture out everything before hand (Attypical for me hahahaha). So I did expect this review, but you spend form my point to much attention to this thoo. Thanks for the feedback anyways!

2) It is you haven't seen the complete implementated version of infineon. 

There I can find the things you mention, it is one hell of a platform related seperations. Typedef this, struct for this, another struct for the struct... Yea, sure so good best practise. 

3) Just for fun I will answer this haha, but actually we should have stopped couple replies ago. 

I believe Ewouts code is not that bad at efficiency, idk why you think it wouldn't, have you tested it? 
I don't have an Embedded company yet, so idk what you are referencing to. 

Well, I think in this case you are scoped too much into the school environment, because don't forget most of them are actually not daily programmers. Also for students like us, we are not daily programmers for production. Sure some program regularly for school projects/assignments but it is just for a short-term educational objective, not a product or codebase contribution.

Finally, offcourse optimalization is always possible. Refactoring is always possible. I can refactor the whole structure for you in 5 workhours, but I would have done it from the start as you mentioned I wouldn't have learned anything new. 

Because the way you would like it, is just what I already could do. But variadic functions are new so I'm playing around. 

Final notice:
To be honest at the start I didn't care about the embedded implementation. I just want the I and Q components so I can start working on feature extraction with DSP and contribute to the prototype realization. 

The conclusion is that this PR escalated haha

2024-04-14 20:41 UTC, closed without merging